// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4Wd_G1erjtRdgm6HGKQLkWsSR8loNUc',
    appId: '1:609224872147:web:17e6abea44eb728b420426',
    messagingSenderId: '609224872147',
    projectId: 'your-choices-project',
    authDomain: 'your-choices-project.firebaseapp.com',
    databaseURL: 'https://your-choices-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'your-choices-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvXNQxh-gwE8SdcO2G0v4cy_di5hiP8Ak',
    appId: '1:609224872147:android:865a41efdd55f43d420426',
    messagingSenderId: '609224872147',
    projectId: 'your-choices-project',
    databaseURL: 'https://your-choices-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'your-choices-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmlXaUQ7nEO1cF9CNGgb4LPPfLSPv436k',
    appId: '1:609224872147:ios:e28e000c369efec0420426',
    messagingSenderId: '609224872147',
    projectId: 'your-choices-project',
    databaseURL: 'https://your-choices-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'your-choices-project.appspot.com',
    androidClientId: '609224872147-lsls5g96l4q70ip4ueq1ubsr3k4agvo8.apps.googleusercontent.com',
    iosClientId: '609224872147-ngfmvr7rf9rbv1pequh16te29im0pc6i.apps.googleusercontent.com',
    iosBundleId: 'com.yourchoices.yourChoices',
  );
}
